name: Python package

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Running tests for ${{ matrix.python-version }} with tox
        uses: ymyzk/run-tox-gh-actions@main
      - name: Publish coverage
        if: ${{ matrix.python-version == 3.9 }}
        run: tox -e coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
